### ISSUE TITLE
pktcMtaDevProvConfigHash

### ISSUE THREAD

**Issue by bajojoba** [jhthorsen/docsis-configfile#4] opened 2015-02-03 12:07 UTC
First of all thumbs up for the module. We use it for configuring 300k+ config files cm+mta.

I was struggling with the pktcMtaDevProvConfigHash.0 that is created with:
my $data = $docsis->encode($config,'sha1');

It is working fine for let's say AVM (Fritz!Box Cable) while with let's say UBEE Cable modem, the mta config fails saying that pktcMtaDevProvConfigHash is not found. I took a closer look at the problem and found out that we have two different oids for the same MIB name!
AVM uses OID: 1.3.6.1.4.1.4491.2.2.1.1.2.7.0 - PKTC-MTA-MIB
UBEE uses OID: 1.3.6.1.4.1.7432.1.1.2.9.0 - PKTC-EXCENTIS-MTA-MIB

Maybe there should also be the third option in array configuring the OIDs above.

Regards,
Janko Bajc

**Comment by jhthorsen** [comment] 2015-02-03 17:05
@bajojoba: Thank you :smile: 

Can you try with the new API? I've completely restructured the module in version 0.65, and I really don't want to fix things in the old version.

https://metacpan.org/pod/DOCSIS::ConfigFile#FUNCTIONS

If you still can reproduce the issue in the latest version 0.68, then please provide proper input data, so I can write a unit test with real data.

**Comment by jhthorsen** [comment] 2015-04-01 13:18
Closing this issue because of lack of information.

**Closed by jhthorsen** 2015-04-01 13:18 UTC
Labels: Bug

**Comment by p-alik** [comment] 2019-10-18 13:20
@jhthorsen, you might find [it](https://github.com/rlaager/docsis/issues/66) interesting.
